apiVersion: v1
kind: Service
metadata:
  name: traffic-sign-service
spec:
  type: NodePort
  selector:
    app: traffic-sign-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
