apiVersion: v1
kind: Service
metadata:
  name: traffic-sign-model-service
spec:
  type: NodePort
  selector:
    app: traffic-sign-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
